# Generated by Django 3.1.4 on 2021-02-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20210209_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='artisan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='client',
            field=models.BooleanField(default=False),
        ),
    ]
