# Generated by Django 3.1.4 on 2021-03-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20210223_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.CharField(blank=True, choices=[('PLUMBER', 'Plumber'), ('ELECTRICIAN', 'Electrician'), ('CARPENTER', 'Carpenter'), ('AC_REPAIRER', 'AC repairer'), ('FASHION_DESIGNER', 'Fashion designer'), ('HAIR_STYLIST', 'Hair stylist'), ('BRICKLAYER', 'Bricklayer'), ('PAINTER', 'Painter')], max_length=150),
        ),
    ]
