# Generated by Django 3.1.4 on 2021-03-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20210309_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=250)),
                ('mywork1', models.CharField(blank=True, max_length=50)),
                ('mywork2', models.CharField(blank=True, max_length=50)),
                ('mywork3', models.CharField(blank=True, max_length=50)),
                ('mywork4', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, choices=[('NIGERIA', 'Nigeria')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.CharField(blank=True, choices=[('PLUMBER', 'Plumber'), ('ELECTRICIAN', 'Electrician'), ('CARPENTER', 'Carpenter'), ('AC_REPAIRER', 'AC repairer'), ('FASHION_DESIGNER', 'Fashion designer'), ('HAIR_STYLIST', 'Hair stylist'), ('BRICKLAYER', 'Bricklayer'), ('PAINTER', 'Painter'), ('WELDER', 'Welder'), ('POP', 'Pop'), ('FURNITURE', 'Furniture'), ('Tiler', 'Tiler'), ('INTERIOR DECORATOR', 'Interior decorator'), ('GENERATOR REPAIRER', 'Generator repairer'), ('TAILOR', 'Tailor'), ('REFRIGERATOR REPAIRER', 'Refrigerator repairer'), ('CLEANER', 'Cleaner'), ('PEST TERMINATOR', 'Pest terminator')], max_length=150),
        ),
    ]
