# Generated by Django 3.1.4 on 2021-03-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20210321_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='portfolio1',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='users/'),
        ),
        migrations.AddField(
            model_name='about',
            name='portfolio2',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='users/'),
        ),
        migrations.AddField(
            model_name='about',
            name='portfolio3',
            field=models.ImageField(default='default.png', null=True, upload_to='users/'),
        ),
        migrations.AddField(
            model_name='about',
            name='portfolio4',
            field=models.ImageField(default='default.png', null=True, upload_to='users/'),
        ),
    ]
