# Generated by Django 3.1.4 on 2021-03-21 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20210321_1054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='Portfolio',
        ),
    ]
